name: CI
on:
    push:
      branches: [ "main" ]
      
jobs:
  linux_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests on linux
        run: |
          python -m unittest circle.py
          python -m unittest rectangle.py
          python -m unittest square.py
          python -m unittest triangle.py

  windows_test:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tests on windows
        run: |
          python -m unittest circle.py
          python -m unittest rectangle.py
          python -m unittest square.py
          python -m unittest triangle.py
